name: CI/CD Pipeline for Parler TTS

on:
  push:
    branches:
      - main  # or whatever branch you use

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub runner setup
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: latest

      - name: Build and Push Docker Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
      
      - name: Build Docker Image
        run: |
          docker build -t docker.pkg.github.com/your-username/your-repo/parler-tts-server:latest .

      - name: Push Docker Image
        run: |
          docker push docker.pkg.github.com/your-username/your-repo/parler-tts-server:latest
